### ISSUE TITLE
Convert attribute frequency data to %

### ISSUE THREAD

**Issue by anthonyrjwood** [anthonyrjwood/soul_again#13]

**Comment by jaybwstu** [comment]
@jaybwstu would you assist me with proof reading the numbers?

**Comment by anthonyrjwood** [comment]
@jaybwstu  would you assist me with proof reading the numbers?

**Comment by anthonyrjwood** [comment]
![Image](https://user-images.githubusercontent.com/56207374/187655516-614931a2-8e79-4b7f-9bfd-3bd827c4fe6b.png)

The distribution table now includes additional columns that display the frequency as a percentage out of 10,000. Proof read simultaneously by Jay when we worked it out.

**Comment by anthonyrjwood** [comment]
![Image](https://user-images.githubusercontent.com/56207374/189844424-25bddf7c-e061-4b1c-8418-8c01db60dd6e.png)

Re-working distribution model to force the compiler to honor our agenda of making the characters "whole again" so we see at least 100 sets of our characters fully built with masks, and then 100 characters fully built without masks.

**Comment by anthonyrjwood** [comment]
const layerConfigurations = [
  {
    growEditionSizeTo: scaleSize(9800),
    layersOrder: [
      { name: "01Habitat", options: {displayName: 'Habitat',}  },
      { name: "02Back Piece", options: {displayName: 'Back Piece',}   },
      { name: "03Horns", options: {displayName: 'Horns',}   },
      { name: "04Ears", options: {displayName: 'Ears',}   },
      { name: "05Body", options: {displayName: 'Body',}   },
      { name: "06Tattoos", options: {displayName: 'Tattoos',}   },
      { name: "07Limbs", options: {displayName: 'Limbs',}   },
      { name: "08Bangles", options: {displayName: 'Bangles',}   },
      { name: "09Eyes", options: {displayName: 'Eyes',}   },
      { name: "10Mouth", options: {displayName: 'Mouth',}   },
      { name: "11Nose", options: {displayName: 'Nose',}   },
      { name: "12Hair", options: {displayName: 'Hair',}   },
      { name: "13Clothing", options: {displayName: 'Clothing',}   },
      { name: "14Strap", options: {displayName: 'Strap',}   },
      { name: "15Medallion", options: {displayName: 'Medallion',}   },
      { name: "16Neck Piece", options: {displayName: 'Neck Piece',}   },
      { name: "17Necklace", options: {displayName: 'Necklace',}   },
      { name: "18Headband", options: {displayName: 'Headband',}   },
    ],
  },
];

const shuffleLayerConfigurations = false;

**Comment by anthonyrjwood** [comment]
Need to adjust again to incorporate 10 fully built characters without masks.

**Comment by anthonyrjwood** [comment]
@

**Comment by anthonyrjwood** [comment]
![Image](https://user-images.githubusercontent.com/56207374/190884051-1b9a51fb-6282-44a5-a1dc-bdfe4f7f7d06.png)
