### ISSUE TITLE
Adding website art

### ISSUE THREAD

**Issue by jaybwstu** [anthonyrjwood/soul_again#16]
For Anthony to build art for the main Soul Again website 
https://soulagain.crypto-elites.club/

**Comment by jaybwstu** [comment]
Banner section 
character1.png 256x350px
This image should be a portrait of character head


![Image](https://user-images.githubusercontent.com/75269155/187437083-b90faae9-f9ae-4190-a531-fe7df011fc06.png)

**Comment by jaybwstu** [comment]
carousel section
carousel_avater(1-7).png 160x170px  7 total
Carousel consists of 7 images, mixture of single attributes or pieces of


![Image](https://user-images.githubusercontent.com/75269155/187439391-4b3f4cce-05ac-433a-ba07-91e3f3473460.png)

**Comment by jaybwstu** [comment]
about us section
Three ideas to discuss
1. Use aboutimage(left/right).png 231x270px  2 total + Use V2_about_bg.png 1920x914px use opaque artwork to texturise the background (could be tattoos, leafs etc) low density. Remove about us cards


![Image](https://user-images.githubusercontent.com/75269155/187449620-af8f3f51-4d60-4723-a464-8896bf80c4aa.png)


2. Use V2_about_bg.png 1920x914px use opaque artwork to texturise the background (could be tattoos, leafs etc) more prominent, higher density image than idea 1. Remove about us cards and about us image left/right


![Image](https://user-images.githubusercontent.com/75269155/187450677-37aad063-a661-47f5-a902-32368b30e9e4.png)


3. Use V2_about_bg.png 1920x914px use opaque artwork to texturise the background (could be tattoos, leafs etc) low density. + about_us_card_icon(1-3).png 50x50px    .3 total, preferably belt attributes or pieces of


![Image](https://user-images.githubusercontent.com/75269155/187451230-d616d138-c1d9-4def-9539-cd12acfb322b.png)

**Comment by jaybwstu** [comment]
#footer


![Image](https://user-images.githubusercontent.com/75269155/187454076-fedfd382-1688-4d16-9a1a-458e172a970e.png)


star 1-7 moving, replace with various leaves or bunches, berries etc, definite

idea 1.
3_chr_img.png 770x400px mask collection overlay (stbf2 loading screen) 

![Image](https://user-images.githubusercontent.com/75269155/187454567-61d3e315-fea5-4d7e-92f5-20adfde98d27.png)

 or; 

v1_footer_bg.png 1920x890px stroke line characters ( full screen image )

**Comment by anthonyrjwood** [comment]
![Image](https://user-images.githubusercontent.com/56207374/187719208-e1603e57-ee87-40d4-80fc-43d64aa6e6dd.png)

**Comment by anthonyrjwood** [comment]
![Image](https://user-images.githubusercontent.com/56207374/187726339-0b1fb5bf-e072-49b8-a545-07de7d089d29.gif)

**Comment by jaybwstu** [comment]
banner section and carousel complete


![Image](https://user-images.githubusercontent.com/75269155/187735679-fa89b8f2-a609-4a1a-8d1d-455180a60858.png)

**Comment by jaybwstu** [comment]
backgrounds
banner


![Image](https://user-images.githubusercontent.com/75269155/193792241-83d4f925-fc18-423f-a2cc-87e967a29db3.png)

about


![Image](https://user-images.githubusercontent.com/75269155/193792384-ecae7c94-e19b-401f-896f-6a48ae906657.png)

team


![Image](https://user-images.githubusercontent.com/75269155/193792466-4024a289-9444-4247-ba35-f4e7b7fcfde5.png)

**Comment by anthonyrjwood** [comment]
https://soulagain.crypto-elites.club/
http://mint.soulagain.crypto-elites.club/ 1920 x 1080 
https://soulagain.crypto-elites.club/coming-soon/
https://crypto-elites.club/#!portfolio.html change icon

**Comment by jaybwstu** [comment]
footer

![Image](https://user-images.githubusercontent.com/75269155/197760020-7d2cb55b-e18d-40a8-abad-b3f6aaf9d92b.png)

**Comment by jaybwstu** [comment]
about


![Image](https://user-images.githubusercontent.com/75269155/197781699-81b81025-9342-4449-8c01-1bb73332df93.png)

**Comment by anthonyrjwood** [comment]
![Image](https://user-images.githubusercontent.com/56207374/197998041-bd1b70fd-071e-4425-91d2-e4fa38837d2e.png)

**Comment by Hser2bio** [comment]
ask better the phantom wallet
![image](https://user-images.githubusercontent.com/38903436/198003630-48bdd1d6-d975-470d-96e8-e4f73bdc43ee.png)

**Comment by anthonyrjwood** [comment]
![Image](https://user-images.githubusercontent.com/56207374/198003537-d19c0ec8-cd41-4e9f-ad9a-fb79301e7bf1.png)



![Image](https://user-images.githubusercontent.com/56207374/198003560-514e050f-71a6-4708-bb22-87579900d681.png)

Optional mint page background images. One standard tiled and the other with a perspective warp / tilt shift / grain / vignette.

**Comment by anthonyrjwood** [comment]
@Hser2bio @jaybwstu Phantom Wallet is also a browser extension? I guess is optional for the user?

**Comment by Hser2bio** [comment]
@anthonyrjwood yes, suggested for solana. Not optional, metamask dont have solana support as far as i know.

**Comment by anthonyrjwood** [comment]
@Hser2bio Ok. I'll get @jaybwstu to update.

**Comment by anthonyrjwood** [comment]
https://bit-flowers.com/images/website_background.rar
