### ISSUE TITLE
Decide final descriptions for main SA site

### ISSUE THREAD

**Issue by anthonyrjwood** [anthonyrjwood/soul_again#20]

**Comment by anthonyrjwood** [comment]
![Image](https://user-images.githubusercontent.com/56207374/187481676-c067a1a3-cfd8-40aa-af6f-643a35c78a6a.png)

**Comment by jaybwstu** [comment]
![Image](https://user-images.githubusercontent.com/75269155/198076267-a33e7a3e-a671-4b4c-86d8-6fcd930c48cc.png)
