### ISSUE TITLE
The possibility of creating an NFT ownership verification channel on Discord.

### ISSUE THREAD

**Issue by anthonyrjwood** [anthonyrjwood/soul_again#27]
Is is possible for Discord users to verify they own a Soul Again NFT in Discord, so they can get access to private channels?

**Comment by anthonyrjwood** [comment]
@Hser2bio

**Comment by Hser2bio** [comment]
Is possible, but i have to check.

I know that exist atleast two options to check by NFT owners by candy machine ID if im not wrong.  

let me some time and i will be write here any news

**Comment by Hser2bio** [comment]
as we talked i tested and works with a single NFT owners, is made by a public bot of Collab land. 

to-do: check deeply if works with candy machine ID

@anthonyrjwood
