### ISSUE TITLE
Changing "Metamask" recommended extension to "Phantom Wallet"

### ISSUE THREAD

**Issue by anthonyrjwood** [anthonyrjwood/soul_again#48]

**Comment by anthonyrjwood** [comment]
Apparently @Hser2bio @jaybwstu it's better to recommend using the phantom wallet, which may require adjusting the "connect" iFrame box from Metamask to Phantom Wallet.

**Comment by jaybwstu** [comment]
modal windows for main site and minting page changed


![Image](https://user-images.githubusercontent.com/75269155/198075920-6a3956ff-4e09-4923-bbae-9d1a61701cb3.png)

**Comment by jaybwstu** [comment]
![Image](https://user-images.githubusercontent.com/75269155/198077093-3fa0ffa1-c202-4f73-9534-6cbdfe1cf85a.png)
